include: package:sizzle_lints/sizzle_lints.yaml

analyzer:
  exclude:
    - "lib/src/core/localization/generated/**"

linter:
  rules:
    avoid_catches_without_on_clauses: true
    cascade_invocations: true